name: Terraform Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod 
  
permissions:
    id-token: write   # This is required for requesting the JWT..
    contents: read
    packages: write
    pull-requests: write 
    
jobs:
  harness_plan:
    name: Harness Plan
    if: github.ref == 'refs/heads/main'
    uses: "./.github/workflows/plan.yml"
    # with:
    #   gh_environment: prod
      # workdir_path: 'organizations'
    secrets:
      TF_VAR_HARNESS_ENDPOINT: ${{ vars.TF_VAR_HARNESS_ENDPOINT }}
      TF_VAR_HARNESS_ACCOUNT_ID: ${{ vars.TF_VAR_HARNESS_ACCOUNT_ID }}
#      TF_VAR_HARNESS_PLATFORM_API_KEY: sat.g-vh4hT8T4KUr9_mnKTaJg.681b4024bbb1cc0cedfec365.U3yd9VGr19l7bDwVwyhq
      TF_VAR_HARNESS_PLATFORM_API_KEY: ${{ secrets.TF_VAR_HARNESS_PLATFORM_API_KEY }}
      # sat.g-vh4hT8T4KUr9_mnKTaJg.685595904faad81e28d7112b.K81H7w76DW2pOD7TwaMR
      BACKEND_RG_NAME: ${{ vars.BACKEND_RG_NAME }}
      BACKEND_STORAGE_ACCOUNT: ${{ vars.BACKEND_STORAGE_ACCOUNT }}
      BACKEND_STORAGE_CONTAINER: ${{ vars.BACKEND_STORAGE_CONTAINER }}
      BACKEND_STORAGE_KEYS: ${{ vars.BACKEND_STORAGE_KEYS }}
      client_id: ${{ vars.client_id }}
      tenant_id: ${{ vars.tenant_id }}
      # AZURE_CREDENTIALS: ${{ vars.AZURE_CREDENTIALS }}

  harness_apply:
    name: Harness Apply
    needs: harness_plan
    uses: "./.github/workflows/apply.yml"
    # with:
    #   gh_environment: prod
      # workdir_path: 'organizations'
    secrets:
      TF_VAR_HARNESS_ENDPOINT: ${{ vars.TF_VAR_HARNESS_ENDPOINT }}
      TF_VAR_HARNESS_ACCOUNT_ID: ${{ vars.TF_VAR_HARNESS_ACCOUNT_ID }}
      # TF_VAR_HARNESS_PLATFORM_API_KEY: sat.g-vh4hT8T4KUr9_mnKTaJg.681b4024bbb1cc0cedfec365.U3yd9VGr19l7bDwVwyhq
      TF_VAR_HARNESS_PLATFORM_API_KEY: ${{ secrets.TF_VAR_HARNESS_PLATFORM_API_KEY }}    
      BACKEND_RG_NAME: ${{ vars.BACKEND_RG_NAME }}
      BACKEND_STORAGE_ACCOUNT: ${{ vars.BACKEND_STORAGE_ACCOUNT }}
      BACKEND_STORAGE_CONTAINER: ${{ vars.BACKEND_STORAGE_CONTAINER }}
      BACKEND_STORAGE_KEYS: ${{ vars.BACKEND_STORAGE_KEYS }}
      client_id: ${{ vars.client_id }}
      tenant_id: ${{ vars.tenant_id }}
      # AZURE_CREDENTIALS: ${{ vars.AZURE_CREDENTIALS }}

